---
- name: Install KNXD
  hosts: image
  remote_user: root
  become_user: root
  become: true

  tasks:
  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Create deb-files directory
    file:
      path: /etc/deb-files/
      state: directory
      mode: 0755

  - name: Copy knxd deb files 0.12
    copy:
      src: "{{ item }}"
      dest: /etc/deb-files/
    with_fileglob:
      - packages/knxd*_0.12*

  - name: Copy knxd deb files 0.14
    copy:
      src: "{{ item }}"
      dest: /etc/deb-files/
    with_fileglob:
      - packages/knxd*_0.14*

  - name: Copy eibd deb
    copy:
      src: packages/eibd_0.0.5-1_armhf.deb
      dest: /etc/deb-files/

  - name: Copy pthsem deb
    copy:
      src: packages/pthsem_2.0.8-1_armhf.deb
      dest: /etc/deb-files/

  - name: Copy eibdscript
    copy:
      src: executables/eibd.sh
      dest: /etc/init.d/eibd
      mode: 0755

  - name: Create eibd User
    user:
      name: eibd
      shell: /usr/sbin/nologin
      groups: users

  - name: eibdconf
    lineinfile:
      path: /etc/ld.so.conf.d/bcusdk.conf
      create: yes
      line: '/usr/local/lib'

  - name: Copy eibd conf
    copy:
      src: configs/eibd.ini
      dest: /etc/default/eibd

  - name: eibdlog
    lineinfile:
      path: /var/log/eibd.log
      create: yes
      line: 'EIBD Log'
      mode: 0777

  - name: List knxd 0.14 deb files
    shell: ls knxd_0.14*.deb
    args:
      chdir: /etc/deb-files/
    register: knxd_files

  - name: Install knxd
    apt: deb="/etc/deb-files/{{ item.1 }}" force=yes state=present
    with_indexed_items: "{{ knxd_files.stdout_lines }}"
    register: knxd
  - debug: var=knxd

#  - name: Install knxd
#    apt:
#      name: knxd
#      state: latest

#  - name: Install knxdtools
#    apt:
#      name: knxd-tools
#      state: latest

  - name: knxd conf add
    copy:
      src: configs/knxd.conf
      dest: /etc/
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: Copy knxd.ini
    copy:
      src: configs/knxd.ini
      dest: /etc/
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: Copy knxd.ini server
    copy:
      src: configs/knxd_IPServer.ini
      dest: /etc/
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: Copy knxd.ini serial
    copy:
      src: configs/knxd_Serial.ini
      dest: /etc/
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: change prio
    blockinfile:
      path: /lib/systemd/system/knxd.service
      block: |
        Nice=-20
        IOSchedulingClass=realtime
        IOSchedulingPriority=0
        CPUSchedulingPolicy=rr
        CPUSchedulingPriority=98
        IOAccounting=True
        IOWeight=5000
      insertafter: "Type=notify"
    ignore_errors: yes

  - name: Stop knxd socket
    systemd: state=stopped name=knxd.socket

  - name: Stop knxd service
    systemd: state=stopped name=knxd.service

  - name: Restart knxd socket
    systemd: state=restarted name=knxd.socket
    register: knxd_socket

  - name: Restart knxd service
    systemd: state=restarted name=knxd.service daemon-reload=yes
    when: knxd_socket

  - name: chmod conf
    file:
      path: /etc/knxd.conf
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: Add dialout
    user:
      name: knxd
      groups: dialout
      append: yes

  - name: udev
    lineinfile:
      path: /etc/udev/rules.d/70-knxd.rules
      create: yes
      line: 'ACTION=="add", SUBSYSTEM=="tty", ATTRS{id}=="00241011", KERNELS=="3f201000.uart", SYMLINK+="ttyKNX1", OWNER="knxd"'

  - name: enable_socket
    systemd: enabled=yes name=knxd.socket
    register: enable_knxd_socket

  - name: enable_service
    systemd: enabled=yes name=knxd.service
    register: enable_knxd_service
