---
- name: nginx reverse proxy
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    packages:
      ["certbot",
      "gzip",
      "nginx-full",
      "geoip-database",
      "geoip-bin",
      "libgeoip1",
      "php7.3-fpm",
      "lua5.1",
      "luarocks",
      "liblua5.1-dev",
      "git",
      "apache2-utils",
      "libnginx-mod-http-lua"
      ]

    build:
      ["git-core",
      "build-essential",
      "autoconf",
      "pkg-config",
      "cmake"]

  tasks:
  - name: easy_dir
    file:
      path: /etc/ssl/easy-rsa
      state: directory
      mode: 0755

  - name: Copy easyrsa
    unarchive:
      src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/EasyRSA-3.0.7.tgz
      dest: /etc/ssl/easy-rsa
      remote_src: yes
      validate_certs: False
      extra_opts: [--strip-components=1]

  - name: Install Buildtools
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      install_recommends: yes
    with_items: "{{ build }}"

  - name: Apachestop
    systemd: state=stopped name=apache2 enabled=no
    ignore_errors: yes

  - name: install apt
    apt:
      name: "{{ item }}"
      state: latest
      install_recommends: no
    with_items: "{{ packages }}"

  - name: Download GeoIP
    get_url:
      url: https://dl.miyuru.lk/geoip/maxmind/country/maxmind4.dat.gz
      dest: /usr/share/GeoIP
    ignore_errors: yes

  - name: Download GeoIP6
    get_url:
      url: https://dl.miyuru.lk/geoip/maxmind/country/maxmind6.dat.gz
      dest: /usr/share/GeoIP
    ignore_errors: yes

  - name: Extract GeoIP
    command: "gunzip -f maxmind4.dat.gz"
    args:
      chdir: /usr/share/GeoIP/
    ignore_errors: yes

  - name: Extract GeoIPv6
    command: "gunzip -f maxmind6.dat.gz"
    args:
      chdir: /usr/share/GeoIP/
    ignore_errors: yes

  - name: Movev4
    copy:
      remote_src: yes
      src: /usr/share/GeoIP/maxmind4.dat
      dest: /usr/share/GeoIP/GeoIP.dat

  - name: Movev6
    copy:
      remote_src: yes
      src: /usr/share/GeoIP/maxmind6.dat
      dest: /usr/share/GeoIP/GeoIPv6.dat

  - name: Deletev4gz
    file:
      path: /usr/share/GeoIP/maxmind4.dat.gz
      state: absent

  - name: Deletev6gz
    file:
      path: /usr/share/GeoIP/maxmind6.dat.gz
      state: absent

  - name: Deletev4
    file:
      path: /usr/share/GeoIP/maxmind4.dat
      state: absent

  - name: Deletev6
    file:
      path: /usr/share/GeoIP/maxmind6.dat
      state: absent

  - name: letsencrypt add
    blockinfile:
      path: /etc/nginx/snippets/letsencrypt.conf
      state: present
      create: yes
      block: |
        location ^~ /.well-known/acme-challenge/ {
         default_type "text/plain";
         root /var/www/letsencrypt;
        }

  - name: Create directory
    file:
      path: /var/www/letsencrypt/.well-known/acme-challenge
      state: directory
      owner: www-data
      group: www-data

  - name: copy_available
    copy:
      dest: /etc/nginx/sites-available/default
      src: configs/nginx_availablesites.conf
      owner: www-data
      group: www-data

  - name: headers
    copy:
      dest: /etc/nginx/headers.conf
      src: configs/nginx_headers.conf
      owner: www-data
      group: www-data

  - name: ticketkey
    shell: "openssl rand 48 > /etc/nginx/nginx_ticketkey"

  - name: proxyconf
    copy:
      dest: /etc/nginx/proxy_params
      src: configs/nginx_proxy.conf
      owner: www-data
      group: www-data

  - name: config
    copy:
      dest: /etc/nginx/nginx.conf
      src: configs/nginx.conf
      owner: www-data
      group: www-data

  - name: Restart1
    systemd: state=restarted name=nginx

  - name: Password1
    command: "htpasswd -cb /etc/nginx/.smartvisu smarthome smarthome"
  - name: Password2
    command: "htpasswd -cb /etc/nginx/.alexa smarthome smarthome"
  - name: Password3
    command: "htpasswd -cb /etc/nginx/.shng smarthome smarthome"
  - name: Password4
    command: "htpasswd -cb /etc/nginx/.monit smarthome smarthome"

  - name: cert_conf
    copy:
      dest: /etc/nginx/conf.d/https.conf
      src: configs/nginx_https.conf
      owner: www-data
      group: www-data

  - name: letsencrypt_ini
    copy:
      dest: /etc/letsencrypt/cli.ini
      src: configs/letsencrypt_cli.ini

  - name: scriptdir
    file:
      path: /etc/nginx/scripts/
      state: directory
      mode: 0755
      group: www-data
      owner: www-data

  - name: luascript
    copy:
      dest: /etc/nginx/scripts/hass_access.lua
      src: configs/nginx_luascript
      owner: www-data
      group: www-data

  - name: Change ini
    replace:
      destfile: /etc/php/7.3/fpm/php.ini
      regexp: ";cgi.fix_pathinfo=1"
      replace: "cgi.fix_pathinfo=0"

  - name: Git crypto
    git:
      repo: 'https://github.com/evanlabs/luacrypto.git'
      dest: /root/luacrypto
      version: master
    register: git
  - debug: var=git

  - name: Install crypto
    command: "luarocks install /root/luacrypto/rockspecs/luacrypto-git-1.rockspec"

  - name: Create lua
    file:
      path: /usr/local/lib/lua/5.1/
      state: directory
      owner: www-data
      group: www-data

  - name: Link
    file:
      dest: '/usr/local/lib/lua/5.1/crypto.so'
      src: '/usr/local/lib/lua/crypto.so'
      state: link
      owner: www-data
      group: www-data

  - name: create phpinfo
    blockinfile:
      mode: 0644
      owner: www-data
      group: www-data
      create: yes
      path: /var/www/html/phpinfo.php
      block: |
        <?php
        // Show all information, defaults to INFO_ALL
        phpinfo();
        ?>

  - name: cgiparam
    lineinfile:
      path: /etc/nginx/fastcgi_params
      insertafter: '(.*)fastcgi_script_name;'
      line: 'fastcgi_param SCRIPT_FILENAME     $document_root$fastcgi_script_name;'

  - name: create favicons dir
    file:
      path: /var/www/html/favicons
      state: directory

  - name: Copy favicons
    unarchive:
      src: configs/favicons.tar
      dest: /var/www/html/favicons/
      owner: smarthome
      group: www-data
      mode: 0770

  - name: create php_systemd dir
    file:
      path: /etc/systemd/system/php7.3-fpm.service.d/
      state: directory

  - name: Copy php_service_conf
    copy:
      src: configs/service_php_directory.conf
      dest: /etc/systemd/system/php7.3-fpm.service.d/
      owner: www-data
      group: www-data
      mode: 0664

  - name: create nginx_systemd dir
    file:
      path: /etc/systemd/system/nginx.service.d/
      state: directory

  - name: Copy service_conf
    copy:
      src: configs/service_nginx_fix.conf
      dest: /etc/systemd/system/nginx.service.d/
      owner: smarthome
      group: smarthome
      mode: 0664

  - name: Copy dnsresolvers
    copy:
      src: executables/dnsresolvers.sh
      dest: /opt/
      owner: smarthome
      group: smarthome
      mode: 0777

  - name: Restart php
    systemd: state=restarted name=php7.3-fpm.service

  - name: Restart nginx
    systemd: state=restarted name=nginx
