---
- name: Install NFS
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    new: '0/24'
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install NFS
    apt: name=nfs-kernel-server force=no state=latest

  - name: Create hosts file
    file: path=/etc/exports state=touch

  - name: clear exports
    lineinfile: dest=/etc/exports state=absent regexp='(.*)'

  - name: Set IP
    set_fact:
      IP: "{{ ansible_default_ipv4.address }}"

  - name: Update IP range
    set_fact:
      NewIP: "{{ IP.split('.')[0] }}.{{ IP.split('.')[1] }}.{{ IP.split('.')[2] }}.{{ new }}"
    register: newip
  - debug: var=newip

  - name: smarthomeuid
    shell: id smarthome | awk -F"[=(]" '{printf "%1s",$2}'
    register: smarthomeuid
  - debug: var=smarthomeuid.stdout

  - name: smarthomegid
    shell: id smarthome|grep "^uid"|awk -F"[=(]" '{printf "%1s",$4}'
    register: smarthomegid
  - debug: var=smarthomegid.stdout

  - name: wwwuid
    shell: id www-data|grep "^uid"|awk -F"[=(]" '{printf "%1s",$2}'
    register: wwwuid

  - name: wwwgid
    shell: id www-data|grep "^uid"|awk -F"[=(]" '{printf "%1s",$4}'
    register: wwwgid

  - name: update exports
    lineinfile: dest=/etc/exports
      line='{{item}}'
    with_items:
      - '/usr/local/smarthome {{ NewIP }}(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ smarthomegid.stdout }}) 10.8.0.0/24(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ smarthomegid.stdout }})'
      - '/var/log {{ NewIP }}(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid=0,anongid=0) 10.8.0.0/24(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid=0,anongid=0)'
      - '/var/www/html/smartvisu {{ NewIP }}(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ wwwgid.stdout }}) 10.8.0.0/24(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ wwwgid.stdout }})'
      - '/var/www/html {{ NewIP }}(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ wwwuid.stdout }},anongid={{ wwwgid.stdout }}) 10.8.0.0/24(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ wwwuid.stdout }},anongid={{ wwwgid.stdout }})'
      - '/home/smarthome {{ NewIP }}(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ smarthomegid.stdout }}) 10.8.0.0/24(no_subtree_check,rw,async,no_wdelay,crossmnt,insecure,no_root_squash,sec=sys,all_squash,anonuid={{ smarthomeuid.stdout }},anongid={{ smarthomegid.stdout }})'

  - name: chmod conf
    file:
      path: /etc/exports
      state: touch
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: exportfs
    command: "exportfs -ra"
    ignore_errors: yes
    register: exportfs
  - debug: var=exportfs

  - name: create rpc_systemd dir
    file:
      path: /etc/systemd/system/rpc-statd.service.d/
      state: directory

  - name: Copy service_rpc
    copy:
      src: configs/service_rpc-statd_fix.conf
      dest: /etc/systemd/system/rpc-statd.service.d/
      owner: smarthome
      group: smarthome
      mode: 0664

  - name: create blkmap_systemd dir
    file:
      path: /etc/systemd/system/nfs-blkmap.service.d/
      state: directory

  - name: Copy service_blkmap
    copy:
      src: configs/service_nfs-blkmap_fix.conf
      dest: /etc/systemd/system/nfs-blkmap.service.d/
      owner: smarthome
      group: smarthome
      mode: 0664

  - name: Enable rpcbind
    systemd: enabled=yes name=rpcbind

  - name: disable nfs
    systemd: enabled=no name=nfs-kernel-server

  - name: disable nfs-blkmap
    systemd: enabled=no name=nfs-blkmap

  - name: disable nfs-utils
    systemd: enabled=no name=nfs-utils
