---
- name: Install Samba
  hosts: all
  remote_user: root
  become_user: root
  become: true

  vars:
    samba_users:
      - name: smarthome
        password: smarthome

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes
   
  - name: Install Samba
    apt: name=samba force=no state=latest

  - name: Copy config
    copy:
      dest: /etc/samba/smb.conf
      src: configs/samba.conf
      owner: smarthome
      group: smarthome
      mode: 0755

  - name: Create Samba users
    shell: >
      (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
      || (echo {{ item.password }}; echo {{ item.password }}) \
      | smbpasswd -s -a {{ item.name }}
    with_items: "{{ samba_users }}"
    register: create_user_output
    changed_when: "'Added user' in create_user_output.stdout"

  - name: Restart smbd
    systemd: state=restarted name=smbd
    notify: Enable smbd

  handlers:
    - name: Enable smbd
      systemd: enabled=yes name=smbd
