---
- name: Install lirc
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Install xsltproc
    apt: name=xsltproc force=no state=latest install_recommends=yes

  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout, video
      append: yes

  - name: Install
    apt: name=lirc force=yes state=latest install_recommends=no

  - name: Copy logrotate
    copy:
      src: configs/logrotate_lircd
      dest: /etc/logrotate.d/lircd

  - name: lirc log
    lineinfile:
      path: /etc/logrotate.d/rsyslog
      insertbefore: BOF
      line: /var/log/lirc.log

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/lirc.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname startswith 'lircd-' then {
          stop
        }
        if $programname startswith 'lircd' or $msg contains 'lircd' then {
          action(type="omfile" file="/var/log/lirc.log" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="smarthome")
          stop
        }
    ignore_errors: yes

#  - name: create systemd dir lirc
#    file:
#      path: /etc/systemd/system/lircd.service.d/
#      state: directory

#  - name: Copy service_conf lirc
#    copy:
#      src: configs/service_lirc_fix.conf
#      dest: /etc/systemd/system/lircd.service.d/
#      owner: smarthome
#      group: smarthome
#      mode: 0644

  - name: Copy devinput
    copy:
      src: configs/devinput.lircd.conf
      dest: /etc/lirc/lircd.conf.d/
      owner: root
      group: root
      mode: 0644

  - name: conf
    lineinfile:
      path: /etc/lirc/lircd.conf
      create: yes
      line: 'include "lircd.conf.d/*.conf"'

  - name: Copy options
    copy:
      src: configs/lirc_options.conf
      dest: /etc/lirc/
      owner: root
      group: root
      mode: 0644

  - name: reload
    command: 'systemctl daemon-reload'

  - name: Stop lirc
    systemd: state=stopped name=lircd.service

  - name: ldconfig
    command: "ldconfig"
    args:
      chdir: /sbin

  - name: disable lircd-setup
    systemd: enabled=no name=lircd-setup.service
  - name: disable lircmd
    systemd: enabled=no name=lircmd.service
  - name: disable lircd-uinput
    systemd: enabled=no name=lircd-uinput.service
  - name: disable irexec
    systemd: enabled=no name=irexec.service

  - name: disable_service
    systemd: enabled=no name=lircd.service

  - name: disable_socket
    systemd: enabled=no name=lircd.socket

  - name: Restart Socket
    systemd: daemon_reload=yes state=restarted name=lircd.socket

  - name: Restart Service
    systemd: daemon_reload=yes state=restarted name=lircd.service
