---
- name: Install Exim4
  hosts: image
  remote_user: root
  become_user: root
  become: true


  tasks:
  - name: Install exim4
    apt: name=exim4 force=no state=latest

  - name: Copy config
    copy:
      src: configs/update-exim4.conf.conf
      dest: /etc/exim4/
      owner: root
      group: root
      mode: 0644

  - name: edit mailadresses
    blockinfile:
      path: /etc/email-addresses
      block: |
        root: mail@domain.com
        logcheck: mail@domain.com
        smarthome: mail@domain.com
    notify: exim4

  - name: change finger
    command: "chfn -f 'SmartHomeNG' root"
    ignore_errors: yes

  - name: mailalias
    lineinfile:
      destfile: /etc/aliases
      line: "root: smarthome"
      insertafter: EOF

  - name: del mailname
    file:
      path: /etc/mailname
      state: absent

  - name: exim4 mailname
    lineinfile:
      destfile: /etc/mailname
      create: yes
      line: "SmartHomeNG"
    ignore_errors: yes

  - name: exim4 syslog
    blockinfile:
      path: /etc/exim4/exim4.conf.localmacros
      create: yes
      block: |
        log_file_path = syslog
        syslog_timestamp = false
        syslog_duplication = false
    ignore_errors: yes

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/exim4.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname startswith 'exim' and $syslogseverity-text == 'info' then {
          action(type="omfile" file="/var/log/exim4/mainlog" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="Debian-exim")
          stop
        }
        if $programname startswith 'exim' and $syslogseverity-text == 'notice' then {
          action(type="omfile" file="/var/log/exim4/rejectlog" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="Debian-exim")
          stop
        }
        if $programname startswith 'exim' and $syslogseverity-text == 'alert' then {
          action(type="omfile" file="/var/log/exim4/paniclog" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="Debian-exim")
          stop
        }

  - name: logrotate
    lineinfile:
      path: /etc/logrotate.d/exim4-base
      regexp: 'compress'
      state: absent

  - name: timeout1
    replace:
      destfile: /etc/exim4/conf.d/main/02_exim4-config_options
      regexp: 'MAIN_IGNORE_BOUNCE_ERRORS_AFTER = (.*)'
      replace: 'MAIN_IGNORE_BOUNCE_ERRORS_AFTER = 1h'

  - name: timeout2
    replace:
      destfile: /etc/exim4/conf.d/main/02_exim4-config_options
      regexp: 'MAIN_TIMEOUT_FROZEN_AFTER = (.*)'
      replace: 'MAIN_TIMEOUT_FROZEN_AFTER = 1h'

  - name: Restart exim4
    systemd: state=restarted name=exim4

  handlers:
  - name: exim4
    systemd: enabled=no name=exim4
    register: exim4
  - debug: var=exim4
