---
- name: Install ansible
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python
    playbooks:
      ["homebridge_Raspi3.yml",
      "influxdb_Raspi3.yml",
      "grafana_Raspi3.yml"
      ]

    configs:
      ["homebridge_config.json",
      "homebridge.service",
      "influxdb.json",
      "logcheck.homebridge"
      ]

    packages:
      [
      ]

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: ansible
    apt: name=ansible force=no state=latest

  - name: sshpass
    apt: name=sshpass force=no state=latest

  - name: change directory
    file:
      path: /etc/ansible
      state: directory
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: create dir1
    file:
      path: /etc/ansible/playbooks/
      state: directory
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: create dir2
    file:
      path: /etc/ansible/configs/
      state: directory
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: create dir3
    file:
      path: /etc/ansible/packages/
      state: directory
      mode: 0755
      owner: smarthome
      group: smarthome

  - name: copy playbooks
    copy:
      dest: /etc/ansible/playbooks/
      src: "additional_playbooks/{{ item }}"
      owner: smarthome
      group: smarthome
    with_items: "{{ playbooks }}"

  - name: copy configs
    copy:
      dest: /etc/ansible/configs/
      src: "configs/{{ item }}"
      owner: smarthome
      group: smarthome
    with_items: "{{ configs }}"

  - name: copy packages
    copy:
      dest: /etc/ansible/packages/
      src: "packages/{{ item }}"
      owner: smarthome
      group: smarthome
    with_items: "{{ packages }}"

  - name: copy hosts
    copy:
      dest: /etc/ansible/hosts
      src: configs/ansible_hosts
      owner: smarthome
      group: smarthome
