---
- name: Install Monit
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    monitgraphpath: /var/www/html/monitgraph

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install monit
    apt:
      name: monit
      state: latest
      update_cache: yes

  - name: Copy monitrc
    copy:
      src: configs/monitrc
      dest: /etc/monit/

  - name: Restart monit service
    systemd: state=restarted name=monit.service

  - name: Monitgraph folder
    file:
      path: "{{ monitgraphpath }}"
      state: directory

  - name: Copy Monitgraph
    unarchive:
      src: packages/monitgraph.tar
      dest: "{{ monitgraphpath }}"

  - name: Monittoken
    file:
      path: /var/www/html/token
      owner: www-data
      group: www-data
      state: touch

  - name: Install curl
    apt: name=php8.2-curl force=no state=latest install_recommends=yes

  - name: make dirs 0755
    command: find "{{ monitgraphpath }}" -type d ! -perm 0755 -exec chmod 0755 {} \;

  - name: make files 0644
    command: find "{{ monitgraphpath }}" -type f ! -perm 0644 -exec chmod 0644 {} \;

  - name: Change Owner
    file:
      path: "{{ monitgraphpath }}"
      owner: www-data
      group: www-data
      recurse: yes
      state: directory

  - name: data folder
    file:
      path: "{{ monitgraphpath }}/data"
      mode: 0777
      state: directory

  - name: data file
    file:
      path: "{{ monitgraphpath }}/data/index.php"
      mode: 0644
      state: touch

  - name: cronjob
    cron:
      name: monitgraph
      user: root
      job: 'php {{ monitgraphpath }}/cron.php >>/var/log/monit-graph.log >/dev/null 2>&1'
      cron_file: monitgraph

  - name: disable cron
    replace:
      destfile: /etc/cron.d/monitgraph
      regexp: "^\\*"
      replace: "#*"
    ignore_errors: yes

  - name: disable monit
    systemd: enabled=no name=monit.service

  - name: favicons folder
    file:
      path: "/var/www/html/favicons"
      mode: 0775
      owner: smarthome
      group: www-data
      state: directory

  - name: favicons
    unarchive:
      src: configs/favicons.tar
      dest: /var/www/html/favicons/
      owner: smarthome
      group: www-data
      mode: 0755

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/monit.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'monit' then {
          action(type="omfile" file="/var/log/monit.log" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="smarthome")
          stop
        }
    ignore_errors: yes

  - name: Copy logrotate
    copy:
      src: configs/logrotate_monit
      dest: /etc/logrotate.d/monit
      mode: 0644
