---
- name: Install OpenVPN
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install openvpn
    apt: name=openvpn force=no state=latest install_recommends=yes

  - name: easy_dir
    file:
      path: /etc/ssl/easy-rsa
      state: directory
      mode: 0755

  - name: Copy easyrsa
    unarchive:
      src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.2/EasyRSA-3.1.2.tgz
      dest: /etc/ssl/easy-rsa
      remote_src: yes
      validate_certs: False
      extra_opts: [--strip-components=1]

  - name: Copy config
    copy:
      src: configs/openvpn.conf
      dest: /etc/openvpn/server.conf
      mode: 0644

  - name: Copy client
    copy:
      src: configs/openvpn_client_example.conf
      dest: /home/smarthome/openvpn_client_example.conf
      mode: 0644

  - name: ip4
    replace:
      destfile: /etc/sysctl.conf
      regexp: "^#net.ipv4.ip_forward=1"
      replace: "net.ipv4.ip_forward=1"
    ignore_errors: yes

  - name: ip6
    replace:
      destfile: /etc/sysctl.conf
      regexp: "^#net.ipv6.conf.all.forwarding=1"
      replace: "net.ipv6.conf.all.forwarding=1"
    ignore_errors: yes

  - name: store sysctl
    shell: "sysctl -p"
    register: sysctl

  - name: Install iptables
    apt: name=iptables-persistent force=no state=latest

  - name: iptables script
    blockinfile:
      path: /usr/local/bin/iptables_openvpn.sh
      mode: 0777
      owner: smarthome
      group: smarthome
      create: yes
      block: |
        #!/bin/bash
        iptables -t filter -F
        iptables -t nat -F
        iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
        iptables -A FORWARD -i tun0 -j ACCEPT
        iptables -A FORWARD -j REJECT
        iptables -t nat -A POSTROUTING -s '10.8.0.0/24' -j MASQUERADE
        iptables-save > /etc/iptables/rules.v4
    register: ready

  - name: Reboot
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: ready is changed

  - name: Wait
    wait_for_connection:
      connect_timeout: 40
      sleep: 15
      delay: 15
      timeout: 400
    when: ready is changed

  - name: run iptables
    shell: "/usr/local/bin/iptables_openvpn.sh"
    register: iptables

  - name: Copy logrotate
    copy:
      src: configs/logrotate_openvpn
      dest: /etc/logrotate.d/openvpn
      mode: 0644

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/openvpn.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'ovpn-server' or $msg contains 'openvpn' then {
          action(type="omfile" file="/var/log/openvpn.log" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm")
          stop
        }
    ignore_errors: yes

  - name: disable openvpnserver
    systemd: enabled=no masked=yes name=openvpn@server.service

  - name: disable openvpn
    systemd: enabled=no name=openvpn.service

  - name: Stop openvpnserver service
    systemd: state=stopped name=openvpn@server.service

  - name: Stop openvpn service
    systemd: state=stopped name=openvpn.service
