---
- name: Install watchdog
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install watchdog
    apt: name=watchdog force=no state=latest install_recommends=no

  - name: edit config
    blockinfile:
      path: /etc/watchdog.conf
      block: |
        watchdog-device = /dev/watchdog
        max-load-1 = 40
        max-load-5 = 20
        file = /var/log/syslog
        min-memory = 1
        watchdog-timeout = 10
        interval = 4
        verbose = 1
        logtick = 120
        log-dir = /var/log/

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/watchdog.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'watchdog' or $msg contains 'watchdog' then {
          action(type="omfile" file="/var/log/watchdog.log" template="FileFormat_timestamp" FileGroup="adm"  FileCreateMode="0644")
          stop
        }
    ignore_errors: yes

  - name: module
    replace:
      destfile: /etc/default/watchdog
      regexp: '^watchdog_module="none"'
      replace: 'watchdog_module="bcm2835_wdt"'
    ignore_errors: yes

  - name: keepalive
    replace:
      destfile: /etc/default/watchdog
      regexp: '^run_wd_keepalive=1'
      replace: 'run_wd_keepalive=0'
    ignore_errors: yes

  - name: nowayout
    lineinfile:
      path: /etc/modprobe.d/bcm2835_wdt.conf
      create: yes
      insertafter: EOF
      line: 'options bcm2835_wdt nowayout=1'

  - name: Copy logrotate
    copy:
      src: configs/logrotate_watchdog
      dest: /etc/logrotate.d/watchdog
      mode: 0644

  - name: Delete_logdir
    file:
      path: /var/log/watchdog
      state: absent

  - name: disbale
    systemd: enabled=no name=watchdog.service
