---
- name: Install Mariadb Backup
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install backup
    apt:
      name: mariadb-backup

  - name: sudoers
    lineinfile:
      path: /etc/sudoers.d/011_mysql
      create: yes
      line: 'mysql ALL=(ALL) NOPASSWD: /usr/bin/mv, /usr/bin/mariabackup, /usr/bin/chmod 0644 /etc/mysql/debian.cnf, /usr/bin/chown mysql\:mysql /etc/mysql/debian.cnf, /usr/bin/chown mysql\:adm /var/log/mysql/mariabackup.log, /usr/bin/chmod 0664 /var/log/mysql/mariabackup.log, /usr/bin/touch /var/log/mysql/mariabackup.log'
      
  - name: Copy script
    copy:
      src: executables/mysql_restore.sh
      dest: /opt/mysql_restore
      mode: 0775
      owner: mysql
      group: mysql

  - name: mybackup_cnf
    copy:
      src: configs/mysql.cnf
      dest: /etc/mysql/backup-my.cnf
      owner: mysql
      group: mysql
      mode: 0644

  - name: Copy cron
    copy:
      src: executables/mysql_backup.sh
      dest: /etc/cron.hourly/mysql_backup
      mode: 0755
      owner: mysql
      group: mysql

  - name: backupdir
    file:
      dest: /var/backups/mysql
      owner: mysql
      group: mysql
      mode: 0770
      state: directory
