---
- name: Install MQTT
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Install paho-mqtt
    pip:
      name: paho-mqtt
      virtualenv: /usr/local/smarthome/venvs/py_311
      virtualenv_site_packages: yes
      state: latest

  - name: Install paho-mqtt 3.10
    pip:
      name: paho-mqtt
      virtualenv: /usr/local/smarthome/venvs/py_310
      virtualenv_site_packages: yes
      state: latest

  - name: Create User
    user:
      name: mosquitto
      shell: /dev/null
      groups: users
      createhome: no
      comment: 'Mosquitto User'

  - name: Install
    apt:
      name: mosquitto
      force: yes

  - name: Install_client
    apt:
      name: mosquitto-clients
      force: yes

  - name: Copy conf
    copy:
      src: configs/mosquitto.conf
      dest: /etc/mosquitto/
      owner: mosquitto
      group: adm
      mode: 0644

  - name: logrotate
    lineinfile:
      path: /etc/logrotate.d/rsyslog
      insertbefore: BOF
      line: /var/log/mosquitto.log

  - name: logfile
    blockinfile:
      path: "/etc/rsyslog.d/mosquitto.conf"
      create: yes
      block: |
        template(name="FileFormat_timestamp" type="string" string= "%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
        if $programname == 'mosquitto' or $msg contains 'Mosquitto' then {
          action(type="omfile" file="/var/log/mosquitto.log" template="FileFormat_timestamp" FileCreateMode="0644" FileGroup="adm" FileOwner="smarthome")
          stop
        }
    ignore_errors: yes

  - name: Groups logcheck
    user:
      name: logcheck
      groups: mosquitto
      append: yes

  - name: Groups logcheck
    user:
      name: logcheck
      groups: adm
      append: yes

  - name: create systemd dir mosquitto
    file:
      path: /etc/systemd/system/mosquitto.service.d/
      state: directory

  - name: Copy service_conf mosquitto
    copy:
      src: configs/service_mosquitto_fix.conf
      dest: /etc/systemd/system/mosquitto.service.d/
      owner: mosquitto
      group: adm
      mode: 0644

  - name: Delete_logdir
    file:
      path: /var/log/mosquitto
      state: absent

  - name: rsyslog
    systemd: daemon_reload=yes state=restarted name=rsyslog.service

  - name: restart
    systemd: daemon_reload=yes state=restarted name=mosquitto.service
