---
- name: Setup Files to config images
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python
    remote_dir: "/opt/setup"

  tasks:
  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: smarthome
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'SmarthomeNG User'

  - name: Groups
    user:
      name: smarthome
      shell: /bin/bash
      groups: www-data, sudo, i2c, adm, audio, video, plugdev, input, netdev, spi, gpio, dialout
      append: yes

  - name: Copy firstboot
    copy:
      src: executables/firstboot.sh
      dest: /usr/local/bin/
      mode: 0777
      owner: smarthome
      group: smarthome

  - name: Copy firstboot service
    copy:
      src: configs/firstboot.service
      dest: /lib/systemd/system/firstboot.service
      owner: root
      group: root
      mode: 0644

  - name: Enable network online
    systemd: enabled=yes name=systemd-networkd-wait-online.service

  - name: enable_firstboot
    systemd: enabled=yes name=firstboot.service

  - name: create dir
    file:
      path: /opt/setup/
      state: directory
      mode: 0755

  - name: Copy setup files
    copy:
      src: "{{ item }}"
      dest: /opt/setup/
      mode: 0755
    with_fileglob:
      - executables/imagesetup/*
