---
- name: Install Homebdrige
  hosts: image
  remote_user: root
  become_user: root
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Install Avahi
    apt: name=libavahi-compat-libdnssd-dev force=no state=latest update_cache=yes

  - name: Install Avahi-Utils
    apt: name=avahi-utils force=no state=latest update_cache=yes

  - name: Update npm
    command: npm install npm@latest -g

  - name: logrotate
    lineinfile:
      path: /etc/logrotate.d/rsyslog
      insertbefore: BOF
      line: /var/lib/homebridge/homebridge.log

  - name: logfile
    blockinfile:
      dest: "/etc/rsyslog.d/homebridge.conf"
      create: yes
      block: |
        $Template FileFormat_timestamp,"%TIMESTAMP% %HOSTNAME% %syslogtag% %pri-text%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
        if $programname == 'homebridge' or $msg contains 'Homebridge'  or $msg contains 'homebridge' then {
          action(type="omfile" file="/var/log/homebridge.log" template="FileFormat_timestamp" FileGroup="adm"  FileCreateMode="0644")
          stop
        }
    ignore_errors: yes

  - name: Install Homebridge
    shell: npm install -g homebridge homebridge-config-ui-x

  - name: Install people
    shell: npm install -g homebridge-people

  - name: Install Forever
    shell: npm install -g forever

  - name: Install Plugin
    shell: npm install -g homebridge-smarthomeng

  - name: Create Group
    group:
      name: smarthome
      state: present

  - name: Create User
    user:
      name: homebridge
      shell: /bin/bash
      groups: smarthome
      append: no
      update_password: always
      password: ""
      comment: 'Homebridge User'

  - name: create dir
    file:
      path: /home/homebridge/.homebridge
      state: directory
      owner: homebridge
      group: smarthome
      mode: 0755

  - name: Copy config
    copy:
      src: configs/homebridge_config.json
      dest: /home/homebridge/.homebridge/config.json
      owner: homebridge
      group: smarthome
      mode: 775

  - name: Copy Logcheck
    copy:
      src: configs/logcheck.homebridge
      dest: /etc/logcheck/ignore.d.server/homebridge
      owner: root
      group: logcheck
      mode: 0644

  - name: Copy service
    copy:
      src: configs/homebridge.service
      dest: /etc/systemd/system/
      owner: homebridge
      group: adm
      mode: 0644

  - name: Stop avahi service
    systemd: state=stopped name=avahi-daemon.service

  - name: disable avahi
    systemd: enabled=no name=avahi-daemon.service

  - name: Restart Service
    systemd: state=restarted name=homebridge.service

  - name: disable homebridge
    systemd: enabled=no name=homebridge.service

  - name: Stop homebridge service
    systemd: state=stopped name=homebridge.service
