---
- name: Install Python 3.6
  hosts: public
  remote_user: root
  become_user: root

  vars:
    buildessentials:
      ["tk-dev",
      "build-essential",
      "checkinstall",
      "libncurses5-dev",
      "libncursesw5-dev",
      "libreadline6-dev",
      "libgdbm-dev",
      "libsqlite3-dev",
      "libssl-dev",
      "libbz2-dev",
      "libexpat1-dev",
      "liblzma-dev",
      "zlib1g-dev",
      "linux-libc-dev"]


  tasks:
  - name: Install Buildessentials
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      install_recommends: yes
    with_items: "{{ buildessentials }}"
    register: apt  
  - debug: var=apt

  - name: Find out Linux Kernel
    shell: uname -r
    register: linuxheader
  - debug: var=linuxheader

  - name: Install Linux Headers
    apt: name="linux-headers-{{linuxheader.stdout}}" state=latest
    ignore_errors: yes
    register: apt  
  - debug: var=apt

  - name: Add src
    replace: 
      destfile: /etc/apt/sources.list 
      regexp: "^#deb-src" 
      replace: "deb-src" 
    ignore_errors: yes
    
  - name: Install git
    apt: name=git force=no state=latest
    register: git  
  - debug: var=git

  - name: Fix
    command: 'apt-get -f -y install'
    register: fix
  - debug: var=fix

  - name: Update Cache
    apt: update_cache=yes

  - name: Safe aptitude upgrade
    apt: upgrade=safe
    register: apt  
  - debug: var=apt
  
  - name: Upgrade Dist
    apt: upgrade=dist
    register: apt
  - debug: var=apt
  
  - stat: path=/etc/deb-files/python_3.6.2-1_armhf.deb
    register: python36deb
    
  - name: Download Python
    get_url:
      url: https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
      dest: /root
      mode: 0777
    register: download  
    when: not python36deb.stat.exists
  - debug: var=download

  - stat: path=/root/Python-3.6.2.tgz
    register: python36tgz

  - name: Extract Python
    unarchive:
      src: /root/Python-3.6.2.tgz
      dest: /root/ 
      remote_src: true  
    register: extract  
    when: python36tgz.stat.exists
  - debug: var=extract

  - name: Remove tgz
    file: path=/root/Python-3.6.2.tgz state=absent
    when: python36tgz.stat.exists

  - stat: path=/root/Python-3.6.2/
    register: python36dir
      
  - name: Running ./configure for Python
    command: '"{{ item }}" chdir=/root/Python-3.6.2/'
    with_items:
      - ./configure
    register: configure  
    when: python36dir.stat.exists
  - debug: var=configure

  - name: Running "make" for Python
    command: '"{{ item }}" chdir=/root/Python-3.6.2/'
    with_items:
      - make
    register: make  
    when: python36dir.stat.exists
  - debug: var=make

  - name: Create Python deb
    command: "checkinstall -D --install=no --fstrans=no --default"
    args:
      chdir: /root/Python-3.6.2/
    register: checkinstall  
    ignore_errors: yes
    when: python36dir.stat.exists
  - debug: var=checkinstall

  - name: Make deb dir
    file: path=/etc/deb-files state=directory
  - name: Copy deb file
    copy: remote_src=True src=/root/Python-3.6.2/python_3.6.2-1_armhf.deb dest=/etc/deb-files
    when: python36dir.stat.exists
  - name: Delete Python dir
    file: path=/root/Python-3.6.2/ state=absent
    when: python36dir.stat.exists

  - name: Install Python 3.6
    apt:
      deb: /etc/deb-files/python_3.6.2-1_armhf.deb
      state: present
    register: python36
  - debug: msg='Python3.6 Installation "{{ python36 }}"'

  - name: Install PIP3
    apt:
      name: python3-pip
      state: latest
      install_recommends: yes
    register: pip3
  - debug: msg='PIP3 Installation "{{ pip3 }}"'

  - name: Install Yolk3k
    pip: name=yolk3k executable=pip3
    register: yolk3k
  - debug: msg='YOLK3K Installation "{{ yolk3k }}"'
